import turtle

turtle.color("gray")
turtle.speed(0)
turtle.pu()
turtle.goto(-200, 200)
turtle.pd()
turtle.bgcolor("green")
turtle.rt(80)
turtle.width(80)
turtle.fd(200)
turtle.pu()
turtle.goto(0, 200)
turtle.rt(20)
turtle.pd()
turtle.fd(200)
turtle.pu()
turtle.goto(-100, -150)
turtle.pd()
turtle.dot(400)
turtle.color("white")
turtle.pu()
turtle.goto(-169, -70)
turtle.pd()
turtle.dot(80)
turtle.color("black")
turtle.dot(50)
turtle.pu()
turtle.goto(-30, -70)
turtle.pd()
turtle.color("white")
turtle.dot(80)
turtle.color("black")
turtle.dot(50)
turtle.pu()
turtle.goto(-100, -270)
turtle.pd()
turtle.color("white")
turtle.dot(100)
turtle.seth(90)
turtle.fd(25)
turtle.color("pink")
turtle.dot(50)
turtle.rt(180)
turtle.width(10)
turtle.fd(50)
turtle.done()