import turtle
RED = turtle.color('red')
# X 1
turtle.color('purple')
turtle.dot(500)
turtle.color('red')
turtle.dot(400)
turtle.color('purple')
turtle.dot(300)
turtle.color('red')
turtle.dot(200)
turtle.color('purple')
turtle.dot(100)

# X 2
turtle.color('red')
turtle.dot(500)
turtle.color('orange')
turtle.dot(417)
turtle.color('yellow')
turtle.dot(334)
turtle.color('green')
turtle.dot(251)
turtle.color('purple')
turtle.dot(168)
turtle.color('plum')
turtle.dot(85)

# X 3
turtle.color('red')
turtle.dot(500)
turtle.color('orange')
turtle.dot(458.5)
turtle.color('yellow')
turtle.dot(417)
turtle.color('red')
turtle.dot(375.5)
turtle.color('orange')
turtle.dot(334)
turtle.color('yellow')
turtle.dot(292.5)
turtle.color('red')
turtle.dot(251)
turtle.color('orange')
turtle.dot(209.5)
turtle.color('yellow')
turtle.dot(168)
turtle.color('red')
turtle.dot(126.5)
turtle.color('orange')
turtle.dot(85)
turtle.color('yellow')
turtle.dot(43.5)

# X 4
turtle.color('blue4')
turtle.dot(500)
turtle.color('blue2')
turtle.dot(458.5)
turtle.color('CadetBlue2')
turtle.dot(417)
turtle.color('LightBlue1')
turtle.dot(375.5)
turtle.color('orange')
turtle.dot(334)
turtle.color("yellow")
turtle.dot(292.5)


# X 5
turtle.color('black')
turtle.dot(500)
turtle.color('red')
turtle.dot(458.5)
turtle.color('black')
turtle.dot(417)
turtle.color('orange')
turtle.dot(375.5)
turtle.color('black')
turtle.dot(334)
turtle.color('yellow')
turtle.dot(292.5)
turtle.color('black')
turtle.dot(251)
turtle.color('red')
turtle.dot(209.5)
turtle.color('black')
turtle.dot(168)
turtle.color('orange')
turtle.dot(126.5)
turtle.color('black')
turtle.dot(85)
turtle.color('yellow')
turtle.dot(43.5)