# Generated by Django 6.0 on 2025-12-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ангилалын нэр')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ангилал',
                'verbose_name_plural': 'Ангилалууд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('detailed_description', models.TextField(verbose_name='Дэлгэрэнгүй тайлбар')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Үнэ')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Хямдрал %')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Үлдэгдэл')),
                ('sku', models.TextField(verbose_name='Барааны код')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зураг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Ангилал')),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүн',
                'verbose_name_plural': 'Бүтээгдэхүүнүүд',
                'ordering': ['-created_at'],
            },
        ),
    ]
