# Generated by Django 5.2.7 on 2025-10-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('birth_date', models.DateField(verbose_name='Birthday')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book name')),
                ('author_name', models.CharField(max_length=200, verbose_name='Author Name')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN Number')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Member Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('join_Date', models.DateField(auto_now_add=True, verbose_name='Registered Day')),
            ],
        ),
    ]
